version: '3'
services:
  toolbox:
    image: node:alpine
    ports:
      - 3500:3500
    volumes:
      - ./:/app
    working_dir: /app
    command: sh -c 'if [ "$NODE_ENV" = "production" ]; then npm install && npm run build && npm run start; else npm install && npm run dev; fi'
