services:
  handyman:
    container_name: main
    image: node:20-alpine
    ports:
      - 3500:3500
    volumes:
      - ./:/app
    working_dir: /app
    command: sh -c 'if [ "${NODE_ENV:-development}" = "production" ]; then yarn && yarn build && yarn start; else yarn install && yarn dev; fi'
