import '@mantine/core/styles.css';

import { BASE_PATH } from '@/config';
import { AppProvider } from '@/providers/app';
import { ColorSchemeScript } from '@mantine/core';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Handyman',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang='en'>
      <head>
        <link rel='icon' href={`${BASE_PATH}/favicon.ico`} sizes='any' />
        <ColorSchemeScript defaultColorScheme='dark' />
      </head>
      <body>
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
